# Generated by Django 3.0.2 on 2020-10-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='shoe_img',
            new_name='problem_img',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='sneaker_name',
            new_name='problem_name',
        ),
    ]
