# Generated by Django 3.0.2 on 2020-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201004_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='problem_name',
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='delhi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='problem_descrition',
            field=models.CharField(default='potholes', max_length=30),
            preserve_default=False,
        ),
    ]
