# Generated by Django 2.2.8 on 2020-11-05 05:35

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20201104_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='generated_title',
            field=models.CharField(default=people.models.select_random_title, max_length=200),
        ),
    ]
