# Generated by Django 2.2.8 on 2020-11-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_generated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='problem_descrition',
            field=models.CharField(max_length=300),
        ),
    ]
